#!/bin/sh

set -e

case "$1" in
       
	purge)

		rm -rf /var/lib/nginx /var/log/nginx /etc/nginx
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        ;;

    *)

        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d nginx remove >/dev/null || exit $?
fi
# End automatically added section


exit 0
